package handlers

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// aiTimeout caps the time a single /ai/* call can spend waiting on
// the Claude SDK. The default is generous (60s) to allow for slow
// large-context completions; the underlying Claude agent also
// applies its own per-call timeout, so this is a defense-in-depth
// upper bound.
const aiTimeout = 60 * time.Second

// maxAIResultBytes caps the raw Claude response we are willing to
// scan with a regex when stripping markdown fences. The prompt asks
// for a JSON array of N short topics; even N=50 fits comfortably
// under 1 MiB.
const maxAIResultBytes = 1 << 20

// AIClient is the contract the AI handler needs from a Claude-like
// agent. Defined here (consumer side) so tests can inject fakes
// without pulling in the Anthropic SDK.
type AIClient interface {
	GenerateTopicsPrompt(seed, platform string, count int) string
	HumanizeScriptPrompt(script string) string
	Complete(ctx context.Context, prompt string) (string, error)
}

// AIHandler exposes AI-assisted endpoints. The /ai/topics endpoint
// returns N differentiated topic ideas generated by Claude for a
// given seed + platform.
type AIHandler struct {
	claude AIClient
	logger *slog.Logger
}

// NewAIHandler wires an AIHandler. A nil logger falls back to
// slog.Default() so callers in main.go do not have to plumb one in.
func NewAIHandler(claude AIClient, logger ...*slog.Logger) *AIHandler {
	l := slog.Default()
	if len(logger) > 0 && logger[0] != nil {
		l = logger[0]
	}
	return &AIHandler{claude: claude, logger: l}
}

// RegisterRoutes attaches the AI endpoints to the router. Currently
// only /ai/topics is exposed; future AI tools (humanize script,
// deconstruct viral) will be added here.
func (h *AIHandler) RegisterRoutes(r gin.IRouter) {
	r.POST("/ai/topics", h.GenerateTopics)
	r.POST("/ai/humanize", h.HumanizeScript)
}

// generateTopicsRequest is the JSON body for POST /ai/topics.
// Validation is explicit (rather than relying on Gin's binding
// defaults) so we can return precise error messages.
type generateTopicsRequest struct {
	Seed     string `json:"seed"`
	Platform string `json:"platform"`
	Count    int    `json:"count"`
}

// generatedTopic is the wire shape for a single topic. Field names
// use snake_case to match the rest of the API (see models/topic.go).
type generatedTopic struct {
	Title               string `json:"title"`
	Angle               string `json:"angle"`
	ExpectedPerformance string `json:"expected_performance"`
	Hook                string `json:"hook"`
}

// generateTopicsResponse wraps the topics array. Wrapping (rather
// than returning a bare array) leaves room for future metadata
// (model version, prompt token count) without breaking clients.
type generateTopicsResponse struct {
	Topics []generatedTopic `json:"topics"`
}

// GenerateTopics — POST /ai/topics
//
// Body: {seed, platform, count}
// 200:  {topics: [...]}
// 400:  invalid body (missing seed/platform, count <= 0)
// 502:  Claude returned output we could not parse as JSON
// 503:  Claude is not configured (no API key) or returned an error
func (h *AIHandler) GenerateTopics(c *gin.Context) {
	var req generateTopicsRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		h.logger.Warn("invalid ai body", "err", err.Error(), "request_id", c.GetString("request_id"))
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request body"})
		return
	}
	req.Seed = strings.TrimSpace(req.Seed)
	req.Platform = strings.TrimSpace(req.Platform)
	if req.Seed == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "seed is required"})
		return
	}
	if req.Platform == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "platform is required"})
		return
	}
	if req.Count <= 0 {
		req.Count = 5
	}
	if req.Count > 20 {
		// Hard cap to keep token usage bounded. Claude's prompt does not
		// impose a limit and a runaway "give me 500" would burn budget.
		req.Count = 20
	}

	prompt := h.claude.GenerateTopicsPrompt(req.Seed, req.Platform, req.Count)

	ctx, cancel := context.WithTimeout(c.Request.Context(), aiTimeout)
	defer cancel()

	raw, err := h.claude.Complete(ctx, prompt)
	if err != nil {
		// Distinguish "Claude is not configured" from generic failures so
		// the frontend can show a useful hint. The agents package uses
		// the literal phrase "no Anthropic API key" — match on that.
		if strings.Contains(err.Error(), "API key") {
			h.logger.Warn("ai: no API key configured", "request_id", c.GetString("request_id"))
			c.JSON(http.StatusServiceUnavailable, gin.H{
				"error": "AI service unavailable: ANTHROPIC_API_KEY not configured on the server",
			})
			return
		}
		h.logger.Error("ai complete failed", "err", err.Error(), "request_id", c.GetString("request_id"))
		c.JSON(http.StatusServiceUnavailable, gin.H{
			"error": "AI service failed: " + err.Error(),
		})
		return
	}

	topics, err := parseTopics(raw)
	if err != nil {
		h.logger.Error("ai parse failed", "err", err.Error(), "request_id", c.GetString("request_id"))
		c.JSON(http.StatusBadGateway, gin.H{
			"error": "AI returned output that could not be parsed: " + err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, generateTopicsResponse{Topics: topics})
}

// jsonArrayRE matches a top-level JSON array, allowing optional
// leading/trailing markdown fences (```json ... ```) and surrounding
// prose. The first non-greedy match is used; the caller validates
// that it parses.
var jsonArrayRE = regexp.MustCompile(`(?s)\[.*?\]`)

// parseTopics extracts a []generatedTopic from a raw Claude
// response. It is lenient about markdown fences and surrounding
// prose because Claude often wraps JSON in ```json ... ``` blocks
// despite explicit instructions.
func parseTopics(raw string) ([]generatedTopic, error) {
	if len(raw) > maxAIResultBytes {
		return nil, errors.New("response too large")
	}
	cleaned := strings.TrimSpace(raw)
	// Strip a single ```json ... ``` wrapper if present.
	if strings.HasPrefix(cleaned, "```") {
		if i := strings.Index(cleaned, "\n"); i >= 0 {
			cleaned = cleaned[i+1:]
		}
		if strings.HasSuffix(cleaned, "```") {
			cleaned = cleaned[:len(cleaned)-3]
		}
		cleaned = strings.TrimSpace(cleaned)
	}
	// If the cleaned output still doesn't start with '[', try to
	// locate the first JSON array in the text.
	if !strings.HasPrefix(cleaned, "[") {
		loc := jsonArrayRE.FindStringIndex(cleaned)
		if loc == nil {
			return nil, errors.New("no JSON array found in response")
		}
		cleaned = cleaned[loc[0]:loc[1]]
	}
	var out []generatedTopic
	if err := json.Unmarshal([]byte(cleaned), &out); err != nil {
		return nil, err
	}
	// Drop entries that are missing the required title — Claude
	// occasionally returns an empty placeholder object.
	filtered := out[:0]
	for _, t := range out {
		if strings.TrimSpace(t.Title) == "" {
			continue
		}
		filtered = append(filtered, t)
	}
	return filtered, nil
}

// humanizeRequest is the JSON body for POST /ai/humanize. The
// frontend sends the full script body and expects a rewritten
// version that reads less like AI-generated text.
type humanizeRequest struct {
	Script string `json:"script"`
}

// humanizeResponse wraps the rewritten script. Wrapping (rather
// than returning a bare string) leaves room for future metadata
// (model version, original vs. rewritten diff).
type humanizeResponse struct {
	Humanized string `json:"humanized"`
}

// HumanizeScript — POST /ai/humanize
//
// Body: {script}
// 200:  {humanized}
// 400:  missing/empty script
// 503:  Claude is not configured (no API key) or returned an error
func (h *AIHandler) HumanizeScript(c *gin.Context) {
	var req humanizeRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		h.logger.Warn("invalid humanize body", "err", err.Error(), "request_id", c.GetString("request_id"))
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request body"})
		return
	}
	req.Script = strings.TrimSpace(req.Script)
	if req.Script == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "script is required"})
		return
	}

	prompt := h.claude.HumanizeScriptPrompt(req.Script)

	ctx, cancel := context.WithTimeout(c.Request.Context(), aiTimeout)
	defer cancel()

	humanized, err := h.claude.Complete(ctx, prompt)
	if err != nil {
		// Distinguish "Claude is not configured" from generic failures
		// so the frontend can show a useful hint. The agents package
		// uses the literal phrase "no Anthropic API key" — match on it.
		if strings.Contains(err.Error(), "API key") {
			h.logger.Warn("humanize: no API key configured", "request_id", c.GetString("request_id"))
			c.JSON(http.StatusServiceUnavailable, gin.H{
				"error": "AI service unavailable: ANTHROPIC_API_KEY not configured on the server",
			})
			return
		}
		h.logger.Error("humanize complete failed", "err", err.Error(), "request_id", c.GetString("request_id"))
		c.JSON(http.StatusServiceUnavailable, gin.H{
			"error": "AI service failed: " + err.Error(),
		})
		return
	}

	c.JSON(http.StatusOK, humanizeResponse{Humanized: humanized})
}
