// apps/api/internal/antiai/antiai.go
// Package antiai implements heuristic anti-AI detection for
// generated text. M1 E: scan text for common AI-generated
// phrases (in Chinese + English) and return a "humanized score"
// in [0, 1]. Lower score = more likely AI-generated.
//
// This is a HEURISTIC check — not a sophisticated ML model. It
// catches obvious AI tells (clichés, disclaimers, "as an AI"
// phrasing) but does NOT detect all AI content. Operators should
// use this as a soft signal, not a hard block. M2 may add
// external GPTZero-style API integration for higher accuracy.
package antiai

import (
	"math"
	"strings"
)

// Result is the output of Check. Score is in [0, 1]; Fails
// lists the specific phrases that triggered the score.
type Result struct {
	Score float64  // 1.0 = no AI tells, 0.0 = saturated with AI tells
	Fails []string // specific phrases that lowered the score
}

// aiPhrases is the M1 list of common AI-generated phrases
// (Chinese + English). Each phrase has an associated weight.
// Phrases are kept lowercase for case-insensitive matching.
//
// Weights are "headcount" of common-AI-tell strength:
//
//	0.30-0.40 = hard tells ("as an AI language model")
//	0.10-0.20 = medium tells ("as an AI assistant")
//	0.05      = light tells (boilerplate closers)
var aiPhrases = []struct {
	Phrase string
	Weight float64
}{
	// Hard tells (0.30-0.40)
	{"作为一名 ai 语言模型", 0.40},
	{"作为一个 ai", 0.30},
	{"作为一个大语言模型", 0.30},
	{"本文由 ai 生成", 0.40},
	{"this response was generated by ai", 0.40},
	{"as an ai language model", 0.30},
	{"i am an ai", 0.30},
	{"i'm an ai", 0.30},
	{"as a large language model", 0.30},
	// Medium tells (0.10-0.20)
	{"作为一个 ai 助手", 0.20},
	{"以上内容仅供参考", 0.15},
	{"希望对您有帮助", 0.10},
	// Light tells (0.05)
	{"请注意", 0.05},
	{"根据您提供", 0.05},
	{"综上所述", 0.05},
}

// Check scans text for AI tells and returns a humanized score.
// The score starts at 1.0 and decreases for each matched phrase.
// Final score is clamped to [0, 1]. Same phrase matched
// multiple times only counts once (dedup).
func Check(text string) Result {
	lower := strings.ToLower(text)
	score := 1.0
	var fails []string
	seen := make(map[string]bool)
	for _, p := range aiPhrases {
		if seen[p.Phrase] {
			continue
		}
		if strings.Contains(lower, p.Phrase) {
			score -= p.Weight
			fails = append(fails, p.Phrase)
			seen[p.Phrase] = true
		}
	}
	if score < 0 {
		score = 0
	}
	return Result{Score: round2(score), Fails: fails}
}

// round2 rounds to 2 decimal places, matching the
// ConsistencyResult.Score style from Sub-Spec A.
func round2(f float64) float64 {
	return math.Round(f*100) / 100
}
