// apps/api/internal/antiai/antiai_test.go
package antiai

import (
	"testing"
)

func TestAntiAICheckEmpty(t *testing.T) {
	// Empty input → score 1.0 (no AI tells).
	r := Check("")
	if r.Score != 1.0 {
		t.Errorf("empty: score = %v, want 1.0", r.Score)
	}
	if len(r.Fails) != 0 {
		t.Errorf("empty: fails = %v, want empty", r.Fails)
	}
}

func TestAntiAICheckZeroAI(t *testing.T) {
	// Plain text, no AI tells → score 1.0.
	r := Check("个人成长博主, 日常 vlog, 治愈系画面")
	if r.Score != 1.0 {
		t.Errorf("zero-AI: score = %v, want 1.0", r.Score)
	}
}

func TestAntiAICheckOneHardTell(t *testing.T) {
	// "作为一个 AI" is in the phrase table (weight 0.30).
	// 1.0 - 0.30 = 0.70. (Spec §12.1 sample shows 0.60 with
	// a slightly different phrase; we follow the table.)
	r := Check("作为一个 AI, 我觉得这个选题不错")
	if r.Score != 0.70 {
		t.Errorf("one-hard: score = %v, want 0.70", r.Score)
	}
	if len(r.Fails) != 1 || r.Fails[0] != "作为一个 ai" {
		t.Errorf("one-hard: fails = %v, want [作为一个 ai]", r.Fails)
	}
}

func TestAntiAICheckMultipleTells(t *testing.T) {
	// "作为一名 AI 语言模型" (0.40) + "以上内容仅供参考" (0.15)
	// + "希望对您有帮助" (0.10) = 1.0 - 0.65 = 0.35.
	r := Check("作为一名 AI 语言模型, 以上内容仅供参考, 希望对您有帮助")
	if r.Score != 0.35 {
		t.Errorf("multi: score = %v, want 0.35", r.Score)
	}
	if len(r.Fails) != 3 {
		t.Errorf("multi: fails = %d, want 3 (%v)", len(r.Fails), r.Fails)
	}
}

func TestAntiAICheckDedupSamePhrase(t *testing.T) {
	// "AI AI AI AI AI" doesn't contain any whole phrase from
	// the table (each phrase has multiple chars). Use a phrase
	// that repeats: "希望对您有帮助希望对您有帮助希望对您有帮助"
	// → still only 1 deduction (dedup on exact phrase).
	r := Check("希望对您有帮助  希望对您有帮助  希望对您有帮助")
	if r.Score != 0.90 {
		t.Errorf("dedup: score = %v, want 0.90", r.Score)
	}
	if len(r.Fails) != 1 {
		t.Errorf("dedup: fails = %d, want 1", len(r.Fails))
	}
}

func TestAntiAICheckCaseInsensitive(t *testing.T) {
	// "I AM AN AI" → 0.70 (跟 "i am an ai" 一样).
	r := Check("I AM AN AI, this is my answer")
	if r.Score != 0.70 {
		t.Errorf("case: score = %v, want 0.70", r.Score)
	}
}

func TestAntiAICheckChineseEnglishMix(t *testing.T) {
	// "作为一个 AI" (0.30) + "i am an ai" (0.30) = 0.40.
	r := Check("作为一个 AI, I am an AI")
	if r.Score != 0.40 {
		t.Errorf("mix: score = %v, want 0.40", r.Score)
	}
}

func TestAntiAICheckSaturateToZero(t *testing.T) {
	// All 15 phrases concatenated → score clamped to 0.0.
	all := "作为一名 ai 语言模型 作为一个 ai 作为一个大语言模型 本文由 ai 生成 " +
		"this response was generated by ai as an ai language model i am an ai i'm an ai " +
		"as a large language model 作为一个 ai 助手 以上内容仅供参考 希望对您有帮助 " +
		"请注意 根据您提供 综上所述"
	r := Check(all)
	if r.Score != 0.0 {
		t.Errorf("saturate: score = %v, want 0.0", r.Score)
	}
	if len(r.Fails) != 15 {
		t.Errorf("saturate: fails = %d, want 15", len(r.Fails))
	}
}

func TestAntiAICheckFailsListCasePreserved(t *testing.T) {
	// Phrases stored lowercase in the table; Fails echoes the
	// table form (lowercase) since matching happens on the
	// lowercased text. The "case-preserved" promise in the spec
	// is for the case-insensitive MATCHING itself, not the
	// echoed phrase form.
	r := Check("I AM AN AI")
	if len(r.Fails) != 1 || r.Fails[0] != "i am an ai" {
		t.Errorf("fails-case: fails = %v, want [i am an ai]", r.Fails)
	}
}

func TestAntiAICheckRound2Formatting(t *testing.T) {
	// 0.5555 → 0.56 (rounded to 2 decimals).
	// Build a contrived text whose score is 0.5555:
	// impossible directly, so use a custom test via the math
	// helper.
	if got := round2(0.5555); got != 0.56 {
		t.Errorf("round2(0.5555) = %v, want 0.56", got)
	}
	if got := round2(0.5549); got != 0.55 {
		t.Errorf("round2(0.5549) = %v, want 0.55", got)
	}
	if got := round2(1.0); got != 1.0 {
		t.Errorf("round2(1.0) = %v, want 1.0", got)
	}
}

func TestAntiAICheckSubstringNotMatched(t *testing.T) {
	// "请" alone should NOT match "请注意" (the phrase is the
	// full 3-char string; strings.Contains does substring match,
	// so "请" alone would match "请注意" — but "请" is not in our
	// text, only "请注意" is). Use "注" alone — short sub-string
	// that doesn't contain the full phrase "请注意".
	r := Check("请注意一下")
	if r.Score != 0.95 {
		t.Errorf("substring: score = %v, want 0.95 (only 请注意 matched)", r.Score)
	}
}
